variables:
  DOCKER_SKIP_BRANCH_BUILD: 1
  DOCKER_SKIP_MERGE_REQUEST_BUILD: 1
  DEPENDENCY_TRACK_PROJECT_ID: 8d7c370b-871a-414f-9b0f-35642728bbe6

include:
  - project: awesome/cicd
    file: common.yml
    ref: v1.0
  - project: awesome/cicd
    file: docker.yml
    ref: v1.0
  - project: awesome/cicd
    file: dependency-track/python.yml
    ref: v1.0    